spring.datasource.url=jdbc:postgresql://localhost:5436/inventorydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=inventoryuser
spring.datasource.password=inventorypass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.h2.console.enabled=false
